import 'package:sinwar_shoping/src/model/product.dart';

import 'category.dart';
import 'address.dart';
import 'order.dart';

class AppData {
  static List<Product> productList = [
    // Existing ones updated
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      category: 'Sneakers',
      images: ['assets/shooe_tilt_1.png', 'assets/shoe_thumb_1.png'],
      price: 240.00,
      discountPrice: 200.00,
      description: 'Comfortable running shoes with Air Max technology.',
      sizes: ['7', '8', '9', '10', '11'],
      colors: ['Black', 'White', 'Red'],
      rating: 4.5,
      reviewCount: 120,
      isFavorite: false,
      isSelected: true,
    ),
    Product(
      id: 2,
      name: 'Nike Air Max 97',
      category: 'Sneakers',
      images: ['assets/shoe_tilt_2.png', 'assets/shoe_thumb_2.png'],
      price: 220.00,
      description: 'Iconic sneakers with visible Air cushioning.',
      sizes: ['7', '8', '9', '10'],
      colors: ['Silver', 'Black'],
      rating: 4.7,
      reviewCount: 95,
      isFavorite: false,
    ),
    // Add more products here
    Product(
      id: 3,
      name: 'Adidas Ultraboost',
      category: 'Sneakers',
      images: ['assets/shoe_thumb_3.png'],
      price: 180.00,
      discountPrice: 150.00,
      description: 'Boost technology for energy return.',
      sizes: ['6', '7', '8', '9', '10', '11', '12'],
      colors: ['Black', 'White', 'Blue'],
      rating: 4.6,
      reviewCount: 200,
    ),
    Product(
      id: 4,
      name: 'Puma RS-X',
      category: 'Sneakers',
      images: ['assets/shoe_thumb_4.png'],
      price: 120.00,
      description: 'Retro style with modern comfort.',
      sizes: ['7', '8', '9', '10'],
      colors: ['Pink', 'Black', 'White'],
      rating: 4.3,
      reviewCount: 80,
    ),
    Product(
      id: 5,
      name: 'Levi\'s Denim Jacket',
      category: 'Jackets',
      images: ['assets/jacket.png'],
      price: 89.99,
      discountPrice: 70.00,
      description: 'Classic denim jacket for everyday wear.',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Blue', 'Black'],
      rating: 4.4,
      reviewCount: 150,
    ),
    Product(
      id: 6,
      name: 'Rolex Submariner',
      category: 'Watches',
      images: ['assets/watch.png'],
      price: 8500.00,
      description: 'Luxury dive watch with Oystersteel.',
      sizes: ['40mm', '41mm'],
      colors: ['Black', 'Green'],
      rating: 4.9,
      reviewCount: 50,
    ),
    Product(
      id: 7,
      name: 'Samsung Galaxy Watch',
      category: 'Watches',
      images: ['assets/watch.png'],
      price: 399.99,
      discountPrice: 349.99,
      description: 'Smartwatch with health tracking.',
      sizes: ['42mm', '46mm'],
      colors: ['Black', 'Silver'],
      rating: 4.5,
      reviewCount: 300,
    ),
    Product(
      id: 8,
      name: 'MacBook Pro 14"',
      category: 'Electronics',
      images: ['assets/macbook.png'], // Assuming asset exists or placeholder
      price: 1999.00,
      description: 'Powerful laptop with M2 chip.',
      sizes: ['14"'],
      colors: ['Space Gray', 'Silver'],
      rating: 4.8,
      reviewCount: 500,
    ),
    Product(
      id: 9,
      name: 'iPhone 15 Pro',
      category: 'Electronics',
      images: ['assets/iphone.png'],
      price: 999.00,
      discountPrice: 949.00,
      description: 'Latest iPhone with Pro camera system.',
      sizes: ['128GB', '256GB', '512GB'],
      colors: ['Natural Titanium', 'Blue Titanium'],
      rating: 4.7,
      reviewCount: 1000,
    ),
    Product(
      id: 10,
      name: 'Sony WH-1000XM5',
      category: 'Electronics',
      images: ['assets/headphones.png'],
      price: 349.99,
      description: 'Noise cancelling wireless headphones.',
      sizes: ['One Size'],
      colors: ['Black', 'Silver'],
      rating: 4.6,
      reviewCount: 400,
    ),
    // Continue adding up to 50
    // For brevity, I'll add a few more, but in practice, generate 50
    Product(
      id: 11,
      name: 'Nike T-Shirt',
      category: 'Clothing',
      images: ['assets/tshirt.png'],
      price: 29.99,
      description: 'Comfortable cotton t-shirt.',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['White', 'Black', 'Gray'],
      rating: 4.2,
      reviewCount: 180,
    ),
    // Add more products
    Product(
      id: 13,
      name: 'Samsung Galaxy S23',
      category: 'Electronics',
      images: ['assets/phone.png'],
      price: 799.99,
      discountPrice: 749.99,
      description: 'Latest Samsung flagship phone.',
      sizes: ['128GB', '256GB'],
      colors: ['Phantom Black', 'Cream'],
      rating: 4.6,
      reviewCount: 800,
    ),
    Product(
      id: 14,
      name: 'Dell XPS 13',
      category: 'Electronics',
      images: ['assets/laptop.png'],
      price: 1299.99,
      description: 'Ultra-portable laptop.',
      sizes: ['13"'],
      colors: ['Silver', 'Black'],
      rating: 4.5,
      reviewCount: 600,
    ),
    // Continue adding up to 50...
    // For brevity, I'll stop here, but in practice, add all 50.
  ];

  // For simplicity, keep cartList as is, but update to match new Product structure
  static List<Product> cartList = [
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      category: 'Sneakers',
      images: ['assets/small_tilt_shoe_1.png'],
      price: 240.00,
      description: 'Comfortable running shoes.',
      sizes: ['10'],
      colors: ['Black'],
      rating: 4.5,
      reviewCount: 120,
    ),
    Product(
      id: 2,
      name: 'Nike Air Max 97',
      category: 'Sneakers',
      images: ['assets/small_tilt_shoe_2.png'],
      price: 190.00,
      description: 'Iconic sneakers.',
      sizes: ['9'],
      colors: ['Silver'],
      rating: 4.7,
      reviewCount: 95,
    ),
    Product(
      id: 3,
      name: 'Adidas Ultraboost',
      category: 'Sneakers',
      images: ['assets/small_tilt_shoe_3.png'],
      price: 220.00,
      description: 'Boost technology.',
      sizes: ['8'],
      colors: ['White'],
      rating: 4.6,
      reviewCount: 200,
    ),
  ];

  static List<Categories> categoryList = [
    Categories(id: 0, name: "All", image: 'assets/all.png', isSelected: true),
    Categories(
      id: 1,
      name: "Sneakers",
      image: 'assets/shoe_thumb_2.png',
      isSelected: false,
    ),
    Categories(
      id: 2,
      name: "Jackets",
      image: 'assets/jacket.png',
      isSelected: false,
    ),
    Categories(
      id: 3,
      name: "Watches",
      image: 'assets/watch.png',
      isSelected: false,
    ),
    Categories(
      id: 4,
      name: "Electronics",
      image: 'assets/electronics.png',
      isSelected: false,
    ),
    Categories(
      id: 5,
      name: "Clothing",
      image: 'assets/clothing.png',
      isSelected: false,
    ),
  ];

  static List<String> showThumbnailList = [
    "assets/shoe_thumb_5.png",
    "assets/shoe_thumb_1.png",
    "assets/shoe_thumb_4.png",
    "assets/shoe_thumb_3.png",
  ];

  static List<Address> addressList = [
    Address(
      id: '1',
      name: 'Home',
      phone: '+1 (555) 123-4567',
      street: '123 Main Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
      isDefault: true,
    ),
    Address(
      id: '2',
      name: 'Office',
      phone: '+1 (555) 987-6543',
      street: '456 Business Ave',
      city: 'New York',
      state: 'NY',
      zipCode: '10002',
      country: 'USA',
      isDefault: false,
    ),
  ];

  static List<Order> orderList = [
    Order(
      id: 'ORD-001',
      items: [
        OrderItem(
          productId: 1,
          productName: 'Nike Air Max 200',
          image: 'assets/shooe_tilt_1.png',
          price: 200.00,
          quantity: 1,
          selectedSize: '10',
          selectedColor: 'Black',
        ),
        OrderItem(
          productId: 5,
          productName: 'Classic Analog Watch',
          image: 'assets/watch_1.png',
          price: 89.99,
          quantity: 1,
          selectedSize: null,
          selectedColor: 'Silver',
        ),
      ],
      subtotal: 289.99,
      shipping: 10.00,
      discount: 0,
      total: 299.99,
      status: OrderStatus.delivered,
      date: DateTime.now().subtract(Duration(days: 15)),
      addressId: '1',
      estimatedDelivery: 'Delivered on Nov 15, 2024',
    ),
    Order(
      id: 'ORD-002',
      items: [
        OrderItem(
          productId: 10,
          productName: 'Premium Winter Jacket',
          image: 'assets/jacket_1.png',
          price: 150.00,
          quantity: 1,
          selectedSize: 'M',
          selectedColor: 'Navy',
        ),
      ],
      subtotal: 150.00,
      shipping: 10.00,
      discount: 10.00,
      total: 150.00,
      status: OrderStatus.shipped,
      date: DateTime.now().subtract(Duration(days: 5)),
      addressId: '1',
      estimatedDelivery: 'Arriving on Dec 5, 2024',
    ),
    Order(
      id: 'ORD-003',
      items: [
        OrderItem(
          productId: 15,
          productName: 'Sports Running Shoes',
          image: 'assets/shoe_thumb_3.png',
          price: 120.00,
          quantity: 2,
          selectedSize: '9',
          selectedColor: 'White',
        ),
      ],
      subtotal: 240.00,
      shipping: 15.00,
      discount: 0,
      total: 255.00,
      status: OrderStatus.processing,
      date: DateTime.now().subtract(Duration(days: 2)),
      addressId: '2',
      estimatedDelivery: 'Arriving on Dec 3, 2024',
    ),
  ];

  static String description =
      "Clean lines, versatile and timeless—the people shoe returns with the Nike Air Max 90. Featuring the same iconic Waffle sole, stitched overlays and classic TPU accents you come to love, it lets you walk among the pantheon of Air. Nothing as fly, nothing as comfortable, nothing as proven. The Nike Air Max 90 stays true to its OG running roots with the iconic Waffle sole, stitched overlays and classic TPU details. Classic colours celebrate your fresh look while Max Air cushioning adds comfort to the journey.";
}
