-- Category/Product indexing and hierarchy helper view
CREATE INDEX idx_parent_id ON CATEGORIES(PARENT_ID);
CREATE INDEX idx_cat_id ON PRODUCTS(CAT_ID);

ALTER TABLE CATEGORIES ADD IS_ACTIVE NUMBER(1) DEFAULT 1;
ALTER TABLE CATEGORIES ADD DISPLAY_ORDER NUMBER;

CREATE OR REPLACE VIEW V_CATEGORIES_HIERARCHY AS
SELECT
  c.ID,
  c.NAME,
  c.PARENT_ID,
  p.NAME AS PARENT_NAME,
  CASE WHEN c.PARENT_ID IS NULL THEN 1 ELSE 0 END AS IS_MAIN_CATEGORY
FROM CATEGORIES c
LEFT JOIN CATEGORIES p ON c.PARENT_ID = p.ID
ORDER BY COALESCE(c.PARENT_ID, c.ID), c.ID;
